input_boolean:
  downstairs_price_adjust:
    name: turn on/off adjustment of downstairs heatpump
    
template:
  sensor: 
  - name: livingroom_temp
    unit_of_measurement: "°C"
    state: >
      {% set lumi = states('sensor.lumi_stue_temperature') %}
      {% set lumi = [] if lumi in ['unavailable', 'unknown'] else [lumi|float] %}
      {% set ws2900 = states('sensor.ws2900_v2_02_02_indoor_temperature') %}
      {% set ws2900 = [] if ws2900 in ['unavailable', 'unknown'] else [ws2900|float] %}
      {% set lumiluft = states('sensor.lumi_luft_temperature') %}
      {% set lumiluft = [] if lumiluft in ['unavailable', 'unknown'] else [lumiluft|float] %}
      {{ (lumi + ws2900 + lumiluft)|average|round(1) }}
  - name: livingroom_temp_adjusted
    unit_of_measurement: "°C"
    state: "{{ states('sensor.livingroom_temp')|float(default=18) - 0.5 * states('sensor.analyzer_updown')|int(default=0) }}"
  - name: livingroom_on
    unit_of_measurement: "°C"
    state: >
      {% set max = state_attr('climate.vpoppe', 'max_temp') %}
      {% set analyzer = states('sensor.analyzer_updown')|int(default=0) %}
      {% set target =  (state_attr('climate.vp_goppe','temperature') + 5 + 0.5 * analyzer)|int %}
      {{ max if target > max else target }}
  - name: livingroom_off
    unit_of_measurement: "°C"
    state: "{{ (state_attr('climate.vp_goppe', 'temperature') + states('sensor.analyzer_updown')|int(default=0))|int }}"
  - name: basement_temp
    unit_of_measurement: "°C"
    state: >
      {% set qp = states('sensor.qp_kjellerstue_temperature') %}
      {% set lumi = states('sensor.lumi_kjeller_temperature') %}
      {% set qp = [] if qp in ['unavailable', 'unknown'] else [qp|float] %}
      {% set lumi = [] if lumi in ['unavailable', 'unknown'] else [lumi|float] %}
      {{ (lumi + qp)|average|round(1) }}
  - name: basement_humidity
    unit_of_measurement: "%"
    state: >
      {% set qp = states('sensor.qp_kjellerstue_humidity') %}
      {% set lumi = states('sensor.lumi_kjeller_humidity') %}
      {% set qp = [] if qp in ['unavailable', 'unknown'] else [qp|float] %}
      {% set lumi = [] if lumi in ['unavailable', 'unknown'] else [lumi|float] %}
      {{ (lumi + qp)|average|round(1) }}

  binary_sensor:
  - name: hot_outside
    state: "{{ states('sensor.netatmo_rypeveien_netatmo_ute_temperature')|float(default=10) > 25 }}"
    delay_on:
      minutes: 20
  - name: hot_livingroom
    state: >
      {{ states('sensor.livingroom_temp')|float(default=20) > 25 }}
    delay_on:
      minutes: 30
  - name: lights_off_for_night
    state: "{{ states('light.livingroom_lights') == 'off' and states('binary_sensor.shellygang_input') == 'off' }}"
  - name: vpnede_onoff
    state: "{{ states('sensor.stikk_vp_nede_power')|int(default=0) > 50 }}"
  - name: vpoppe_onoff
    state: "{{ states('sensor.stikk_vp_oppe_power')|int(default=0) > 20 }}"
  - name: schedule_adjust
    state: >
      {% set holiday_until = as_datetime(states('input_datetime.holiday_until')).timestamp() %}
      {% set schedule = states('schedule.livingroom_schedule') %}
      {{ now().timestamp() > holiday_until and schedule == 'on' }}

switch: 
  - platform: template
    switches: 
      vpoppe_onoff:
#        value_template: "{{ states('sensor.stikk_vp_oppe_power')|int(default=0) > 50 }}"
        turn_on:
          service: climate.set_temperature
          target:
            entity_id: climate.vpoppe
          data:
            temperature: >
              {% set max = state_attr('climate.vpoppe', 'max_temp') %}
              {% set analyzer = states('sensor.analyzer_updown')|int(default=0) %}
              {% set target =  (state_attr('climate.vp_goppe','temperature') + 5 + 0.5 * analyzer)|int %}
              {{ max if target > max else target }}
        turn_off:
          service: climate.set_temperature
          target:
            entity_id: climate.vpoppe
          data:
            temperature: "{{ state_attr('climate.vp_goppe', 'temperature') + states('sensor.analyzer_updown')|int(default=0) }}"
      vpnede_onoff:
        value_template: "{{ states('sensor.stikk_vp_nede_power')|int(default=0) > 50 }}"
        turn_on:
        turn_off:

climate:
  - platform: generic_thermostat
    name: vp_goppe
    heater: switch.vpoppe_onoff
    target_sensor: sensor.livingroom_temp_adjusted
    target_temp_step: 0.5
    min_cycle_duration: 600
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_temp: 17
    max_temp: 28
  - platform: generic_thermostat
    name: vp_gnede
    heater: switch.vpnede_onoff
    target_sensor: sensor.basement_temp
    target_temp_step: 1
    min_temp: 17
    max_temp: 28

schedule:
  livingroom_schedule:
    name: "Livingroom schedule"
    monday: 
      - from: "07:30:00"
        to: "10:30:00"
      - from: "15:00:00"
        to: "21:00:00"
    tuesday:
      - from: "15:00:00"
        to: "21:00:00"
    wednesday:
      - from: "07:30:00"
        to: "11:30:00"
      - from: "14:30:00"
        to: "21:00:00"
    thursday: 
      - from: "15:00:00"
        to: "21:00:00"
    friday: 
      - from: "14:30:00"
        to: "21:00:00"
    saturday:
      - from: "09:00:00"
        to: "21:00:00"
    sunday:
      - from: "09:00:00"
        to: "21:00:00"

automation: 
  - id: '1658673475311'
    alias: 'Climate VP Oppe Start cooling '
    description: ''
    trigger:
    - platform: template
      value_template: >
        {{ states('binary_sensor.hot_livingroom') == 'on'
           and states('binary_sensor.hot_outside')  == 'on'
           and states('sensor.pvlogger_power')|int(default=0) > 2000
           and states('binary_sensor.dor_inngang_on') == 'off'
           and states('binary_sensor.verandador_contact') == 'off' }}
    condition:
    - condition: state
      entity_id: climate.vpoppe
      state: 'off'
    action:
    - service: climate.set_hvac_mode
      target:
        entity_id:
          - climate.vpoppe
      data:
        hvac_mode: cool
    - service: climate.set_temperature
      data:
        temperature: 25
      target:
        entity_id: climate.vpoppe
    mode: single

  - id: '1658673749726'
    alias: Climate VP oppe Turn off when idle for 20 hours
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.stikk_vp_oppe_power
      for:
        hours: 30
        minutes: 0
        seconds: 0
      below: '50'
    condition:
    - condition: state
      entity_id: climate.vpoppe
      state: 'cool'
    action:
    - service: climate.set_hvac_mode
      target:
        entity_id:
          - climate.vpoppe
      data:
        hvac_mode: off
    mode: single

  - id: '1663912913996'
    alias: Analyzer-adjust heat-pump upstairs temperature 
    trigger:
      - platform: template
        value_template: >
          {{ now().minute < 59 and state_attr('climate.vp_goppe', 'temperature') + 
             states('sensor.analyzer_updown')|int  +
             (1 if states('binary_sensor.schedule_adjust') == 'on' else 0) != 
             state_attr('climate.vpoppe','temperature') }}
      - platform: state
        entity_id: binary_sensor.dor_inngang_open
        id: door_open
      - platform: state
        entity_id: binary_sensor.verandador_open
        id: verandador_open
    condition:
      - condition: template
        value_template: >
          {{ states('sensor.analyzer_updown') in ['-1', '0', '1'] }}
      - condition: template
        value_template: >
          {{ trigger.entity_id != 'sensor.analyzer_updown' or 
             trigger.from_state.state in ['-1', '0', '1'] }}
      - condition: template
        value_template: "{{ now().minute < 59 }}"
      - condition: state
        entity_id: climate.vp_goppe
        state: 'heat'
    action:
      - choose:
        - conditions: 
          - condition: template
            value_template: "{{ states('climate.vpoppe') == 'heat' }}"
          sequence: 
          - service: climate.set_temperature
            data: 
              temperature: >
                {{ 17 if (states('binary_sensor.dor_inngang_open') == 'on' or states('binary_sensor.verandador_open') == 'on') else 
                   state_attr('climate.vp_goppe', 'temperature') + 
                   states('sensor.analyzer_updown')|int +
                   (1 if states('binary_sensor.schedule_adjust') == 'on' else 0)  }}
            target:
              entity_id: climate.vpoppe
        - conditions: 
          - condition: template
            value_template: "{{ states('climate.vpoppe') == 'cool' }}"
          sequence: 
          - service: climate.set_temperature
            data: 
              temperature: >
                {{ state_attr('climate.vp_goppe', 'temperature') - states('sensor.analyzer_updown')|int }}
            target:
              entity_id: climate.vpoppe

  - id: '1663912913997'
    alias: Analyzer-adjust heat-pump downstairs temperature 
    trigger:
      - platform: template
        value_template: >
          {{ now().minute < 59 and state_attr('climate.vp_gnede', 'temperature') + states('sensor.analyzer_updown')|int(default=0) != 
             state_attr('climate.vpnede','temperature') and states('binary_sensor.zwift_active') == 'off' }}
    condition:
      - condition: state
        entity_id: input_boolean.downstairs_price_adjust
        state: 'on'
      - condition: template
        value_template: >
          {{ states('sensor.analyzer_updown') in ['-1', '0', '1'] }}
      - condition: template
        value_template: >
          {{ trigger.entity_id != 'sensor.analyzer_updown' or 
             trigger.from_state.state in ['-1', '0', '1'] }}
      - condition: template
        value_template: "{{ now().minute < 59 }}"
      - condition: state
        entity_id: climate.vp_gnede
        state: 'heat'
    action:
      - choose:
        - conditions: 
          - condition: template
            value_template: "{{ states('climate.vpnede') == 'heat' }}"
          sequence: 
          - service: climate.set_temperature
            data: 
              temperature: >
                {{ state_attr('climate.vp_gnede', 'temperature') + states('sensor.analyzer_updown')|int(default=0) }}
            target:
              entity_id: climate.vpnede
        - conditions: 
          - condition: template
            value_template: "{{ states('climate.vpnede') == 'cool' }}"
          sequence: 
          - service: climate.set_temperature
            data: 
              temperature: >
                {{ state_attr('climate.vp_gnede', 'temperature') - states('sensor.analyzer_updown')|int(default=0) }}
            target:
              entity_id: climate.vpnede

  - id: '202501161251'
    alias: Set heatpump fanmode according to people home or away and sleeping
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.anyone_home
          - binary_sensor.lights_off_for_night
    action:
      - choose: 
        - conditions: 
          - condition: template
            value_template: "{{ state_attr('climate.vpoppe','fan_mode') != 'high' }}"
          - condition: or
            conditions: 
            - condition: state
              entity_id: binary_sensor.anyone_home
              state: 'off'
            - condition: state
              entity_id: binary_sensor.lights_off_for_night
              state: 'on'
          sequence:
            - service: climate.set_fan_mode
              target:
                entity_id: climate.vpoppe
              data:
                fan_mode: high
        - conditions: 
          - condition: template
            value_template: "{{ state_attr('climate.vpoppe','fan_mode') != 'auto' }}"
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'
          - condition: state
            entity_id: binary_sensor.lights_off_for_night
            state: 'off'
          sequence:
          - service: climate.set_fan_mode
            target:
              entity_id: climate.vpoppe
            data:
              fan_mode: auto

  - id: '202501171253'
    alias: Adjust upstairs heatpump set temperature if condition changes
    trigger:
      - platform: state
        entity_id: 
          - sensor.livingroom_on
          - sensor.livingroom_off
    action:
      - choose:
        - conditions:
          - condition: state
            entity_id: switch.vpoppe_onoff
            state: 'on'
          - condition: template
            value_template: >
              {{ state_attr('climate.vpoppe','temperature') != states('sensor.livingroom_on')|int }}
          sequence: 
            - service: climate.set_temperature
              data: 
                temperature: "{{ states('sensor.livingroom_on') }}"
              target:
                entity_id: climate.vpoppe
        - conditions:
          - condition: state
            entity_id: switch.vpoppe_onoff
            state: 'off'
          - condition: template
            value_template: >
              {{ state_attr('climate.vpoppe','temperature') != states('sensor.livingroom_off')|int }}
          sequence: 
            - service: climate.set_temperature
              data: 
                temperature: "{{ states('sensor.livingroom_off') }}"
              target:
                entity_id: climate.vpoppe

