input_select:
  vacuum_target:
    options:
      - Idle
      - Ukentlig
      - Stue
      - Kjøkken
      - Gang
      - Soverom
  
timer:
  vacuum_timer:
    duration: "96:00:00"
    restore: true

automation:
  - id: '202412281132'
    alias: vacuum on select
    trigger: 
      - platform: state
        entity_id: input_select.vacuum_target
      - platform: state
        entity_id: vacuum.roborock_s8
        to: "docked"
        id: docked
    action:
    - choose: 
      - conditions:
        - condition: trigger
          id: docked
        sequence:
          - service: input_select.select_option
            target: 
              entity_id: input_select.vacuum_target
            data:
              option: 'Idle'
          - if:
            - condition: numeric_state
              entity_id: sensor.roborock_s8_cleaning_area
              above: 35
            then: 
            - service: timer.cancel
              target:
                entity_id: timer.vacuum_timer
            - delay:
                minutes: 1
            - service: timer.start
              target:
                entity_id: timer.vacuum_timer
      - conditions:
        - condition: state
          entity_id: input_select.vacuum_target
          state: 'Ukentlig'
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_s8
          data:
            command: app_segment_clean
            params: 
              - segments:
                - 16 # LivingRoom
                - 23 # Corridor
                - 19 # Kitchen
      - conditions:
        - condition: state
          entity_id: input_select.vacuum_target
          state: 'Stue'
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_s8
          data:
            command: app_segment_clean
            params: 
              - segments:
                - 16 # LivingRoom
      - conditions:
        - condition: state
          entity_id: input_select.vacuum_target
          state: 'Gang'
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_s8
          data:
            command: app_segment_clean
            params: 
              - segments:
                - 23 # Corridor
      - conditions:
        - condition: state
          entity_id: input_select.vacuum_target
          state: 'Kjøkken'
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_s8
          data:
            command: app_segment_clean
            params: 
              - segments:
                - 19 # Kitchen
      - conditions:
        - condition: state
          entity_id: input_select.vacuum_target
          state: 'Soverom'
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_s8
          data:
            command: app_segment_clean
            params: 
              - segments:
                - 17 # MasterBedroom
#                - 20 # Study1
#                - 21 # Study
        
  - id: '1644566778718'
    alias: Støvsug Mandag og Fredag når ingen er hjemme
    description: ''
    trigger:
    - platform: time
      at: '14:00'
      id: cleaningtime
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: "off"
      for: 
        minutes: 15
      id: home_alone
    - platform: template
      value_template: >
        {{ states('binary_sensor.anyone_home') == 'on' }}
      id: noenkommerhjem
    condition: 
    - condition: state
      entity_id: input_boolean.fenrir_pa_besok
      state: "off"
    - condition: or
      conditions:
        - condition: trigger
          id: 
          - cleaningtime
          - noenkommerhjem
        - condition: state
          entity_id: timer.vacuum_timer
          state: 'idle'
    action:
    - choose:
      - conditions:
        - condition: or
          conditions:
          - condition: trigger
            id: home_alone
          - condition: and
            conditions: 
            - condition: trigger
              id: cleaningtime
            - condition: state
              entity_id: binary_sensor.anyone_home
              state: 'off'
        - condition: or
          conditions:
          - condition: time
            after: '13:00'
            before: '14:15'
            weekday:
            - mon
            - fri
          - condition: state
            entity_id: timer.vacuum_timer
            state: 'idle'
        - condition: state
          entity_id: vacuum.roborock_s8
          state: "docked"
        sequence:
          - service: input_select.select_option
            target: 
              entity_id: input_select.vacuum_target
            data:
              option: 'Ukentlig'
      - conditions:
        - condition: trigger
          id: noenkommerhjem
        sequence:
        - choose:
          - conditions:
            - condition: state
              entity_id: binary_sensor.roborock_s8_cleaning
              state: "on"
            sequence:
            - service: vacuum.pause
              data: {}
              target:
                entity_id: vacuum.roborock_s8
            - wait_template: "{{ states('vacuum.roborock_s8') == 'paused' }}"
              continue_on_timeout: true
              timeout: "60"
            - service: vacuum.return_to_base
              data: {}
              target:
                entity_id: vacuum.roborock_s8
          - conditions:
            - condition: state
              entity_id: vacuum.roborock_s8
              state: error
            sequence:
            - delay:
                hours: 0
                minutes: 2
                seconds: 0
                milliseconds: 0
            - service: media_player.volume_set
              data:
                volume_level: 0.3
              target:
                entity_id: media_player.stue
            - service: tts.google_translate_say
              data:
                entity_id: media_player.stue
                language: 'no'
                message: 'Hei, og velkommen hjem. Jeg har forsøkt å støvsuge, men har
                  satt meg fast. Kan du hjelpe meg ? '
            - delay:
                hours: 0
                minutes: 0
                seconds: 10
                milliseconds: 0
            - service: vacuum.locate
              data: {}
              target:
                entity_id: vacuum.roborock_s8
          default: []
      default: []
    mode: single
